### ISSUE TITLE
Lights are found, but not changing color

### ISSUE THREAD

**Issue by RomanDeNu** [carstena/game-to-philips-hue#3]
Image files are being created and deleted, but the lights aren't changing color.  The lights are found to populate the drop down.  

Last image processed in:
0ms |null

**Comment by carstena** [comment]
Can you place the content of your config.properties file? Which operating system and version do you have?

**Comment by carstena** [comment]
Does your path param, in config.properties, has trailing slashes?

**Comment by RomanDeNu** [comment]
When I get home from work, I'll reinstall and let you know.

**Comment by 4waymedia** [comment]
I am encountering the same issue. If I run Fraps for a few sec, I get screenshots in the folder. . . As soon as I click Start in the Epic Game Lighting for Hue window, the screenshots are removed, and the status updated, and then goes to 0ms |null

The light(s) never change.

Windows 8.1

username=slickdev
ip=12.0.1.5
refreshrate=1000
path=F:\fraps\

**Comment by carstena** [comment]
And if you change your path to: F:\\fraps\\

Does that work?

**Comment by carstena** [comment]
I've uploaded version 1.2. This new version improves the error handling and gives better error messages.
